# Example configuration entry
esphome:
  name: d1-dimmer

# Restore from flash if you want to keep the last state at power up
esp8266:
  board: esp8285
  restore_from_flash: true

# Make sure your WiFi will connect
wifi:
  networks:
  - ssid: !secret wifi_ssid_home1 
    password: !secret wifi_password_home1
  - ssid: !secret wifi_ssid_my_home2
    password: !secret wifi_password_my_home2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1 Fallback Hotspot"
    password: !secret ap_password

# Make sure logging is not using the serial port
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

# Make sure you can upload new firmware OTA
ota:
  platform: esphome

status_led:
  pin:
    number: 13
    inverted: true

# D1 dimmer uses hardware serial port on the default pins @ 9600 bps
uart:
  rx_pin: RX
  tx_pin: TX
  baud_rate: 9600

# And finally the light component
# gamma correction equal to zero gives linear scale,
# exactly what's needed for this device
light:
  - platform: sonoff_d1
    use_rm433_remote: False
    name: Sonoff D1 Dimmer
    restore_mode: RESTORE_DEFAULT_OFF
    gamma_correct: 0.0
    default_transition_length: 1s

